name: terraform - test - azure/application-gateway

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.application-gateway.yml
      - azure/application-gateway/*.tf
      - azure/application-gateway/*.hcl
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.application-gateway.yml
      - azure/application-gateway/*.tf
      - azure/application-gateway/*.hcl

jobs:
  test:
    uses: ./.github/workflows/tf.test.yml
    with:
      tf_path: azure/application-gateway
      tf_version: latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
